<?php
/**
 * @var \Amasty\StorePickupWithLocator\Block\Location $block
 * @var \Amasty\Storelocator\Model\Location $location
 */
$locations = $block->getLocationCollection();
?>
<div class="amlocator-wrapper">
    <div class="amlocator-stores-wrapper">
        <?php foreach ($locations as $location): ?>
            <div class="amlocator-store-desc" name="leftLocation"
                 data-mapid="<?= $block->escapeHtml($block->getMapId()); ?>"
                 data-amid="<?= (int)$location['id']; ?>">
                <div class="amlocator-block">
                    <?php
                    // Fix for incompatibility with old amasty-pickup module, will be obsolete
                    // when amasty/module-store-locator version >=2.4.4 is used
                    // Change: $location => $location->getId()
                    ?>
                    <?php if ($baseImage = $block->getLocationImage($location->getId())): ?>
                        <div class="amlocator-image"
                             style="background-image:
                                     url('<?= $block->escapeUrl($baseImage) ?>')">
                        </div>
                    <?php endif; ?>
                    <div class="amlocator-store-information">
                        <?= /* @noEscape */
                        $location->getStoreListHtml() ?>
                        <button class="amlocator-button -pickup"
                                data-ampickup-location="<?= (int)$location->getId() ?>"
                                data-ampickup-js="choose-store"
                                title="<?= $block->escapeHtml(__('Pick up here')); ?>">
                            <?= $block->escapeHtml(__('Pick up here')); ?>
                        </button>
                    </div>
                </div>
                <?=
                $block->getLayout()
                    ->createBlock(\Amasty\Storelocator\Block\View\Schedule::class)
                    ->setData('location', $location)
                    ->toHtml();
                ?>
            </div>
        <?php endforeach; ?>
    </div>

    <?php if ($pager = $block->getPagerHtml()): ?>
        <div class="amlocator-pager-container"><?= /** @escapeNotVerified */
            $pager; ?></div>
    <?php endif; ?>
</div>
