<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<div class="item link compare" data-bind="scope: 'compareProducts'" data-role="compare-products-link">
    <a class="action compare" title="<?= /* @escapeNotVerified */ __('Compare Products') ?>"
       data-bind="attr: {'href': compareProducts().listUrl}">
        <!-- ko if: compareProducts().count -->
            <span class="counter qty" data-bind="text: compareProducts().count"></span>
        <!-- /ko -->
    </a>
</div>
<script type="text/x-magento-init">
{"[data-role=compare-products-link]": {"Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>}}
</script>
