<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    $_layer = $this->getLayer();
    $_category = $_layer->getCurrentCategory();
    $categoryTemplate = $_category->getCategoryTemplate();

    if ($categoryTemplate == 1) {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_second_template';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    } elseif ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <ol class="products list items product-items">
             <?php
             /** @var \Lightweight\Extra\Helper\Data $helperExtra */
             $helperExtra = $this->helper('Lightweight\Extra\Helper\Data');
             ?>
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
            <li class="item product product-item">
                <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
                 <div class="image-container">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <?php
                        $isNew = $helperExtra->isProductNew($_product);
                        if($isNew): ?>
                            <div class="new-badge"></div>
                        <?php endif; ?>
                        <?php if($_product->getSpecialPrice() && $helperExtra->isProductOnSale($_product) && $_product->getSpecialPrice() < $_product->getPrice() && !$isNew && !$helperExtra->getHidePurchaseInfos()) : ?>
                            <div class="sale-badge"></div>
                        <?php endif; ?>
                        </div>
                    <div class="product-details-wrapper">
                        <div class="product details product-item-details">
                            <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </strong>
                             <div style="display:none" data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                            <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                        <?php endif; ?>
                                    </div>
                            <?php if ($categoryTemplate != 1): ?>
                                <?= '<div class="product-item-type"><span>'.$_helper->productAttribute($_product, $_product->getAttributeText('lw_product_type'), 'lw_product_type'). '</span></div>' ?>
                                <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                                <?php if(!$helperExtra->getHidePurchaseInfos()): ?>
                                    <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                                <?php endif; ?>
                                <?= $block->getProductDetailsHtml($_product) ?>
                            <?php endif; ?>
                            <div class="product-item-inner">
                                <?php if ($categoryTemplate != 1): ?>
                                <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                    <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                     <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>">
                                            <button title="<?= $block->escapeHtml(__('Learn More')) ?>"
                                                    class="action primary">
                                                    <span><?= /* @escapeNotVerified */ __('Learn More') ?></span>
                                            </button>
                                        </a>
                                    </div>
                                </div>
                                <?php endif; ?>
                                <?php if ($showDescription):?>
                                    <div class="product description product-item-description">
                                        <?php if ($_product->getSeriesDescription()) {
                                            echo /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getSeriesDescription(), 'series_description');
                                        } else {
                                            echo /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description');
                                        } ?>
                                        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>">
                                            <button title="<?= $block->escapeHtml(__('To the series')) ?>"
                                                class="action primary">
                                                    <span><?= /* @escapeNotVerified */ __('To the series') ?></span>
                                            </button>
                                        </a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
